### ISSUE TITLE
Mismatch pretrained model and checkpoint

### ISSUE THREAD

**Issue by DianaZhongHua** [ChiShengChen/ResVMamba#1]
Hi, 
Thank you for your contribution. I am very interested in your project so I am trying to run it by myself. However, I cannot replicate the best-weight Res-VMamba model on CNFOOD-241-Chen you shared on Hugging Face. The config.json, in the first place, is not a valid JSON file. Also, I tried to load the state_dict in the checkpoint file "[ckpt_epoch_166.pth](https://huggingface.co/ms57rd/Res-VMamba/blob/main/ckpt_epoch_166.pth") to the proposed VSSM_small model, but it seems like they are not the same size. The ckpt_epoch_166.pth is for ImageNet since the class number is 1000 instead of 241.
<img width="1303" alt="image" src="https://github.com/ChiShengChen/ResVMamba/assets/40658533/9a2b06a4-69ae-49c5-a435-998894418e2a">
I would appreciate it if you could help with clarifying this problem. Is my misunderstanding or it's a wrong update? Thank you so much!

**Comment by ChiShengChen** [comment]
@DianaZhongHua , thanks for reading our work! You did't misunderstand anything, the model class is still 1000 is because we only change the data file to the CNFOOD-241, the data file folder structure is the same as the imagenet, but only input 241 classes of data.
If you has some reproduced result, it is welcome to share with us!

**Comment by DianaZhongHua** [comment]
Hi ChiSheng,
Thank you for your prompt response to my previous query about using the CNFOOD-241 dataset with the 1000-class model structure. I'm curious about the specifics of how the 241 classes are mapped to the model's 1000-class output layer.

Could you shed some light on how you handle the mapping during training and inference? Are there certain indices within the 1000 classes that are designated for CNFOOD-241, or do you apply any post-processing to filter out the predictions for the non-existing classes?

Any details you can provide would be greatly helpful for my understanding. Thank you!

**Comment by ChiShengChen** [comment]
Hi @DianaZhongHua , the reason that the class input in model is 1000 is because I use the original imagenet dataloader but input the CNFOOD241 data folder, and according to my understanding, although the input class is 1000, but the model weight still can train with the classes under the 1000 (like 241) still works fine. You can see the `build.py` for detail:
https://github.com/ChiShengChen/ResVMamba/blob/6acf302b22296f500e889d9d7653a73e1817ce95/data/build.py#L129

I have re-run the code, and it worked fine  in my environment on a 3080:
![Screenshot from 2024-03-27 01-20-07](https://github.com/ChiShengChen/ResVMamba/assets/22126443/2103a361-226e-4d1d-aae9-effda3ed4ebe)
